@startuml
Px2d --> Px2d : 14096
0x20 --> 0x20 : 64541
Px2e --> 0x20 : 131
digit --> Px2e : 1650
Px2f --> alpha : 50
Px2d --> 0x0d : 101
0x20 --> digit : 3911
digit --> 0x0d : 274
Px2d --> digit : 163
0x20 --> alpha : 2514
Px2d --> alpha : 4
0x0a --> Px2d : 51
0x0a --> 0x0d : 4
Px2e --> alpha : 6
Px2e --> digit : 1650
alpha --> Px29 : 26
digit --> 0x20 : 3254
Px2d --> 0x20 : 50
Px3a --> Px2d : 50
0x20 --> Px28 : 2
alpha --> Px3a : 175
Px3a --> 0x0d : 300
0x0a --> 0x20 : 500
Px2c --> 0x20 : 77
alpha --> alpha : 13257
Px28 --> digit : 1
Px28 --> alpha : 26
alpha --> Px2c : 26
0x0a --> alpha : 351
Px2e --> Px29 : 1
Px3a --> 0x20 : 1925
alpha --> Px2d : 29
alpha --> Px2e : 15
Px29 --> 0x20 : 27
Px3a --> alpha : 75
alpha --> 0x0d : 176
0x20 --> Px3a : 1700
Px2e --> Px3a : 5
alpha --> Px2f : 75
0x0a --> [*] : 1
0x20 --> Px2d : 188
alpha --> 0x20 : 2505
digit --> alpha : 1
0x20 --> Px2e : 129
digit --> Px3a : 495
digit --> digit : 4788
0x0d --> 0x0a : 907
0x20 --> 0x0d : 51
Px2e --> 0x0d : 1
Px2c --> digit : 848
Px3a --> Px28 : 25
Px2f --> 0x20 : 25
digit --> Px2c : 899
[*] --> 0x20 : 1
@enduml
